# Generated by Django 4.0.2 on 2022-02-13 19:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GameApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamecycle',
            name='attractions',
        ),
        migrations.AlterField(
            model_name='gamecycle',
            name='kikoriks',
            field=models.ManyToManyField(related_name='usersInGame', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи'),
        ),
    ]
