# Generated by Django 4.0.2 on 2022-02-13 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameApp', '0002_remove_gamecycle_attractions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kikorik',
            name='happinesK',
            field=models.FloatField(default=0.5, verbose_name='HK'),
        ),
        migrations.AlterField(
            model_name='attractions',
            name='cultureK',
            field=models.FloatField(verbose_name='Культ.-познават. (C)'),
        ),
        migrations.AlterField(
            model_name='attractions',
            name='eventsK',
            field=models.FloatField(verbose_name='Событийный (E)'),
        ),
        migrations.AlterField(
            model_name='attractions',
            name='fatigue',
            field=models.FloatField(verbose_name='Усталость (F)'),
        ),
        migrations.AlterField(
            model_name='attractions',
            name='gameDay',
            field=models.IntegerField(verbose_name='Игровой день (GDay)'),
        ),
        migrations.AlterField(
            model_name='attractions',
            name='healthK',
            field=models.FloatField(verbose_name='Лечебн.-оздоров. (H)'),
        ),
        migrations.AlterField(
            model_name='attractions',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Тур. объект (A)'),
        ),
        migrations.AlterField(
            model_name='attractions',
            name='recreationK',
            field=models.FloatField(verbose_name='Рекреация (R)'),
        ),
        migrations.AlterField(
            model_name='attractions',
            name='sportK',
            field=models.FloatField(verbose_name='Спортивный (S)'),
        ),
        migrations.AlterField(
            model_name='kikorik',
            name='cultureK',
            field=models.FloatField(verbose_name='Культ.-познават. (C)'),
        ),
        migrations.AlterField(
            model_name='kikorik',
            name='eventsK',
            field=models.FloatField(verbose_name='Событийный (E)'),
        ),
        migrations.AlterField(
            model_name='kikorik',
            name='fatigue',
            field=models.FloatField(verbose_name='Усталость (F)'),
        ),
        migrations.AlterField(
            model_name='kikorik',
            name='healthK',
            field=models.FloatField(verbose_name='Лечебн.-оздоров. (H)'),
        ),
        migrations.AlterField(
            model_name='kikorik',
            name='recreationK',
            field=models.FloatField(verbose_name='Рекреация (R)'),
        ),
        migrations.AlterField(
            model_name='kikorik',
            name='sportK',
            field=models.FloatField(verbose_name='Спортивный (S)'),
        ),
    ]
