# Generated by Django 4.0.2 on 2022-02-14 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameApp', '0003_kikorik_happinesk_alter_attractions_culturek_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamecycle',
            old_name='kikoriks',
            new_name='usersInGame',
        ),
        migrations.AddField(
            model_name='gamecycle',
            name='gameDate',
            field=models.DateField(blank=True, null=True, verbose_name='Дата проведения'),
        ),
        migrations.AddField(
            model_name='gamecycle',
            name='isActive',
            field=models.BooleanField(default=False, verbose_name='Статус (Вкл/Выкл)'),
        ),
        migrations.AlterField(
            model_name='attractions',
            name='gameDay',
            field=models.IntegerField(default=1, verbose_name='Игровой день (GDay)'),
        ),
    ]
