# Generated by Django 4.0.2 on 2022-02-14 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameApp', '0004_rename_kikoriks_gamecycle_usersingame_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attractions',
            name='iconUrl',
            field=models.URLField(blank=True, verbose_name='Иконка'),
        ),
        migrations.AddField(
            model_name='kikorik',
            name='iconUrl',
            field=models.URLField(blank=True, verbose_name='Иконка'),
        ),
    ]
