# Generated by Django 4.0.2 on 2022-02-14 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameApp', '0005_attractions_iconurl_kikorik_iconurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attractions',
            name='iconUrl',
        ),
        migrations.RemoveField(
            model_name='kikorik',
            name='iconUrl',
        ),
        migrations.AddField(
            model_name='attractions',
            name='icon',
            field=models.ImageField(null=True, upload_to='', verbose_name='Фотография'),
        ),
        migrations.AddField(
            model_name='kikorik',
            name='icon',
            field=models.ImageField(null=True, upload_to='', verbose_name='Фотография'),
        ),
    ]
