# Generated by Django 4.0.2 on 2022-02-14 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameApp', '0006_remove_attractions_iconurl_remove_kikorik_iconurl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kikorik',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание смешарика'),
        ),
    ]
