# Generated by Django 4.0.2 on 2022-02-14 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameApp', '0008_alter_kikorik_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamecycle',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='Название'),
        ),
    ]
