# Generated by Django 4.0.2 on 2022-02-15 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameApp', '0009_gamecycle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamecycle',
            name='isEnded',
            field=models.BooleanField(default=False, verbose_name='Игра закончилась?'),
        ),
        migrations.AddField(
            model_name='gamecycle',
            name='isPaused',
            field=models.BooleanField(default=False, verbose_name='Игра на паузе?'),
        ),
        migrations.AddField(
            model_name='kikorik',
            name='isTurnMade',
            field=models.BooleanField(default=False, verbose_name='Персонаж сходил?'),
        ),
        migrations.AlterField(
            model_name='gamecycle',
            name='isActive',
            field=models.BooleanField(default=False, verbose_name='Игра активна?'),
        ),
    ]
