# Generated by Django 4.0.2 on 2022-02-15 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameApp', '0010_gamecycle_isended_gamecycle_ispaused_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attractions',
            name='ecoK',
            field=models.FloatField(null=True, verbose_name='Экологический (Eco)'),
        ),
        migrations.AddField(
            model_name='attractions',
            name='isForRelax',
            field=models.BooleanField(default=False, verbose_name='Создан для отдыха?'),
        ),
        migrations.AddField(
            model_name='kikorik',
            name='ecoK',
            field=models.FloatField(null=True, verbose_name='Экологический (Eco)'),
        ),
    ]
