# Generated by Django 4.0.2 on 2022-02-15 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GameApp', '0011_attractions_ecok_attractions_isforrelax_kikorik_ecok'),
    ]

    operations = [
        migrations.CreateModel(
            name='MakeTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameDay', models.IntegerField(blank=True, verbose_name='Игровой день')),
                ('attractionFive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AttractionFive', to='GameApp.attractions', verbose_name='Достопримечательность №5')),
                ('attractionFour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AttractionFour', to='GameApp.attractions', verbose_name='Достопримечательность №4')),
                ('attractionOne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AttractionOne', to='GameApp.attractions', verbose_name='Достопримечательность №1')),
                ('attractionThree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AttractionThree', to='GameApp.attractions', verbose_name='Достопримечательность №3')),
                ('attractionTwo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AttractionTwo', to='GameApp.attractions', verbose_name='Достопримечательность №2')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MadeTurn',
            fields=[
                ('maketurn_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='GameApp.maketurn')),
                ('fatigueOne', models.FloatField(verbose_name='Усталость №1')),
                ('fatigueTwo', models.FloatField(verbose_name='Усталость №2')),
                ('fatigueThree', models.FloatField(verbose_name='Усталость №3')),
                ('fatigueFour', models.FloatField(verbose_name='Усталость №4')),
                ('fatigueFive', models.FloatField(verbose_name='Усталость №5')),
                ('happinesOne', models.FloatField(verbose_name='HK №1')),
                ('happinesTwo', models.FloatField(verbose_name='HK №2')),
                ('happinesThree', models.FloatField(verbose_name='HK №3')),
                ('happinesFour', models.FloatField(verbose_name='HK №4')),
                ('happinesFive', models.FloatField(verbose_name='HK №5')),
            ],
            bases=('GameApp.maketurn',),
        ),
    ]
